# Fancy Indexing

Literally just passing an array of indices to index multiple elements.

In [1]:
import numpy as np

rng =  np.random.default_rng(seed=1)

x = rng.integers(100, size=10)
print(x)

[47 51 75 95  3 14 82 94 24 31]


In [2]:
indices = [3, 7, 4]
print(x[indices])

[95 94  3]


The shape of the ouput is the shape of the index array, not the original array.

In [3]:
indices = np.array([
    [3, 7],
    [4, 5]
])
print(x[indices])

[[95 94]
 [ 3 14]]


You can use fancy indexing to modify the original array

In [7]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


However, they do NOT behave like slices.

In [ ]:
y = x[i]
y[0] = 9999
print(y)
print(x)