# Test

welcome to my test notebook!

In [19]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [20]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[ 0.02900434 -0.42877933 -0.694372   -1.02396513]
 [-0.17048844 -0.0146749  -0.79751437  1.57820395]
 [ 0.33625155 -0.57784241 -0.74644125 -0.54737158]
 [ 0.31484774 -0.28025507  0.52573953  0.15134503]]


wowowowowo