# Test

welcome to my test notebook!

In [7]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [8]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[ 0.23904626  0.55908163  0.16610814  0.74665366]
 [ 0.26478792 -0.42695585 -0.6137619   0.96507247]
 [ 0.27060161  0.77915141  1.4144165   1.26809169]
 [ 1.82455479  0.54910848  0.3520049  -0.08813127]]


wowowowowo