# Test

welcome to my test notebook!

In [23]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [24]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[-0.02198    -0.34187822 -0.63973644  2.11067629]
 [-0.72044878 -0.32374139 -0.99367478 -0.94534054]
 [-0.47906471 -1.12877653  1.98232006  0.07112477]
 [-0.78180722 -0.61094717 -0.42921758  0.21811032]]


wowowowowo