# Test

welcome to my test notebook!

In [13]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [14]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[-0.04906905 -0.75498156  0.12662583 -0.90209969]
 [-0.55334494 -0.59493997  0.10320947 -0.04820116]
 [ 0.61343812 -0.84161029 -0.10959028  0.52334805]
 [-0.00862338  0.30868573  0.17564203  0.3193761 ]]


wowowowowo