# Test

welcome to my test notebook!

In [21]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [22]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[-1.48204427  1.37132124 -0.46143929  0.19297336]
 [ 0.48885853 -1.89150806  1.13172786 -0.68629401]
 [ 1.81429044 -0.17465655 -0.38742997 -1.53833767]
 [ 0.67812106  0.34864331  0.1815442  -2.5558644 ]]


wowowowowo