# Test

welcome to my test notebook!

In [15]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [16]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[-0.78269496  2.04078516 -1.39252104 -1.1263867 ]
 [ 1.66694703 -1.31832984  0.315714    1.65883776]
 [ 0.66375775  0.01382612 -1.29162426  1.41949792]
 [-1.80964635  0.4524345   0.65824488  0.04491102]]


wowowowowo