# Test

welcome to my test notebook!

In [1]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [2]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[ 0.74163502 -1.04928163  1.84419911  0.22103028]
 [ 0.29897688  0.26827459  1.30662687  1.31117524]
 [-1.04020468  0.7110022   0.61161923 -0.1415119 ]
 [-0.91744124  1.54814413  0.59044942 -0.97255118]]


wowowowowo