# Test

welcome to my test notebook!

In [11]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [12]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[-2.3219415  -0.44796793 -0.60702893 -1.34310241]
 [ 0.97025672 -0.80950429  0.19817032 -1.32009431]
 [-0.94073532 -0.59486839 -1.04376753  1.30661442]
 [ 1.54650431 -0.13255233 -0.00305204 -0.714024  ]]


wowowowowo