# Test

welcome to my test notebook!

In [9]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [10]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[ 0.59459848  0.41554308  0.56082336  0.39167646]
 [ 0.58472736 -0.1344113  -1.08038265  0.2191855 ]
 [ 1.21230516  0.33939485 -0.09032228  2.28736808]
 [-0.11604987 -0.33023779 -0.7013646  -1.53661089]]


wowowowowo