# Test

welcome to my test notebook!

In [17]:
print('hello world!')

hello world!


# Markdown cell

This is a markdown cell

In [18]:
import numpy as np

x = np.random.normal(0, 1, (4, 4))
print(x)

[[ 0.63659881 -0.7547004   2.48262174 -1.56119534]
 [-1.29964809  0.13811662  0.32076859  0.44897702]
 [-0.09517348  1.9160572   0.54426281 -0.33350432]
 [ 1.04672861 -1.73680278  1.04846718  0.45787182]]


wowowowowo